export let dumbbellStore = [
  {
    id: 1,
    item: "Dumbbell",
    type: "5kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/KR/IV/MY-10225761/rubber-dumbbell-set-5-kg-500x500.jpg",
  },
  {
    id: 2,
    item: "Dumbbell",
    type: "6kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://static-01.daraz.pk/p/128657491c2afcdab8e62e858b254341.jpg_340x340q80.jpg_.webp",
  },
  {
    id: 3,
    item: "Dumbbell",
    type: "8kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://www.rebelsport.com.au/dw/image/v2/BBRV_PRD/on/demandware.static/-/Sites-srg-internal-master-catalog/default/dwfed7cfb9/images/378857/Rebel_378857_hi-res.jpg?sw=1000&sh=1000&sm=fit",
  },
  {
    id: 4,
    item: "Dumbbell",
    type: "10kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/LE/ZU/KF/SELLER-62786957/10kg-rubber-dumbbell-500x500.jpg",
  },
  {
    id: 5,
    item: "Dumbbell",
    type: "12kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://static-01.daraz.pk/p/c8a61e53e882ad352e0792588a9fd907.jpg",
  },
  {
    id: 6,
    item: "Dumbbell",
    type: "15kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/XR/HN/ZH/SELLER-30915340/2-5-kg-rubber-coated-hex-dumbbell-500x500.jpeg",
  },
  {
    id: 7,
    item: "Dumbbell",
    type: "17.5kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://images-na.ssl-images-amazon.com/images/I/81EbppNbPhL.jpg",
  },
  {
    id: 8,
    item: "Dumbbell",
    type: "20kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://m.media-amazon.com/images/I/71Vck9EdEJL._AC_SL1500_.jpg",
  },
  {
    id: 9,
    item: "Dumbbell",
    type: "30kg",
    material: "Rubber",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/QT/JX/NJ/SELLER-5211951/dumbbells-500x500.jpg",
  },
  {
    id: 10,
    item: "Dumbbell",
    type: "5kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://static-01.daraz.pk/p/d8afd378802bc25b90b48f956c76f549.jpg",
  },
  {
    id: 11,
    item: "Dumbbell",
    type: "6kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/61TKJTnMdjL._SL1500_.jpg",
  },
  {
    id: 12,
    item: "Dumbbell",
    type: "8kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://sc02.alicdn.com/kf/Hdff96a03f9334166996e3a8f98b6acfa9/231685485/Hdff96a03f9334166996e3a8f98b6acfa9.jpg_.webp",
  },
  {
    id: 13,
    item: "Dumbbell",
    type: "10kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://m.media-amazon.com/images/I/51-ZiDQD+2L._SX425_.jpg",
  },
  {
    id: 14,
    item: "Dumbbell",
    type: "12kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://rukminim1.flixcart.com/image/416/416/kit/e/e/s/protoner-14-kg-steel-dumbbell-set-original-imaefspktfbhkcc8.jpeg?q=70",
  },
  {
    id: 15,
    item: "Dumbbell",
    type: "15kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://m.media-amazon.com/images/I/71yrA8pctWL._SL1500_.jpg",
  },
  {
    id: 16,
    item: "Dumbbell",
    type: "17.5kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://n4.sdlcdn.com/imgs/a/v/b/Saifi-Sports-17-5kg-Steel-SDL446817191-1-5bcb8.jpg",
  },
  {
    id: 17,
    item: "Dumbbell",
    type: "20kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/IB/LY/MY-21798609/20-kg-steel-dumbbell-500x500.jpg",
  },
  {
    id: 18,
    item: "Dumbbell",
    type: "30kg",
    material: "Steel",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://image.made-in-china.com/43f34j00kyREaKOqnSpb/Wholesale-Stainless-Steel-Dummbell-15-20-25-30kg-with-Low-Price.jpg",
  },
];

export let machines = [
  {
    id: 1,
    item: "Machine",
    type: "Butterfly",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/QC/WF/MY-67695863/butterfly-machine-500x500.jpg",
  },
  {
    id: 2,
    item: "Machine",
    type: "Commando",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://5.imimg.com/data5/XN/TE/BT/SELLER-3525058/commando-100-magnetic-core-drill-machine-500x500.jpg",
  },
  {
    id: 3,
    item: "Machine",
    type: "Press",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://esskaymachines.com/blog/wp-content/uploads/2019/03/power-press-machine-500x500.jpg",
  },
];

export let benches = [
  {
    id: 1,
    item: "Bench",
    type: "Straight",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image:
      "https://www.atlantisstrength.com/wp-content/uploads/2018/07/B-178.jpg",
  },
  {
    id: 2,
    item: "Bench",
    type: "Inclined",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://4.imimg.com/data4/BM/CF/MY-8634398/1-500x500.jpg",
  },
  {
    id: 3,
    item: "Bench",
    type: "Three in One",
    price: "PKR 3000",
    availability: "Available",
    company: "Builderon ki shan, Mazdoor ki aan, ghareebon ka dumbbell",
    image: "https://static-01.daraz.pk/p/2b217a6a19b4fcf7c5276ca4451ea6f0.jpg",
  },
];
